# Generated by Django 5.2.6 on 2025-09-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='msal_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='msal_oid',
        ),
        migrations.AddField(
            model_name='user',
            name='is_microsoft_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='microsoft_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
