# Generated by Django 5.2.6 on 2025-09-18 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('latest_period', models.CharField(blank=True, max_length=50, null=True)),
                ('latest_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('latest_ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('latest_pat', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('latest_market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('latest_enterprise_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('latest_ev_revenu', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('exchange_ticker', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('summary', models.JSONField(default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/finance/')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pat', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('enterprise_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ev_revenu', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.company')),
            ],
            options={
                'unique_together': {('company', 'period')},
            },
        ),
    ]
