# Generated by Django 5.2.6 on 2025-09-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='company',
            name='latest_pat',
        ),
        migrations.RemoveField(
            model_name='company',
            name='latest_revenue',
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='pat',
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='revenue',
        ),
        migrations.AddField(
            model_name='company',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='headquarters_country_region',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_classifications',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='latest_total_revenue',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_industry',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_sector',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='total_revenue',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='exchange_ticker',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='latest_ebitda',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='latest_enterprise_value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='latest_ev_revenu',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='latest_market_cap',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='ebitda',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='enterprise_value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='ev_revenu',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='period',
            field=models.CharField(default='latest', max_length=50),
        ),
    ]
