# Generated by Django 5.2.6 on 2025-09-19 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_financialrecord_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='latest_ebitda',
        ),
        migrations.RemoveField(
            model_name='company',
            name='latest_enterprise_value',
        ),
        migrations.RemoveField(
            model_name='company',
            name='latest_ev_revenu',
        ),
        migrations.RemoveField(
            model_name='company',
            name='latest_market_cap',
        ),
        migrations.RemoveField(
            model_name='company',
            name='latest_period',
        ),
        migrations.RemoveField(
            model_name='company',
            name='latest_total_revenue',
        ),
    ]
