# Generated by Django 5.2.6 on 2025-09-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_company_latest_ebitda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry_classifications',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
