# Generated by Django 5.2.6 on 2025-10-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_company_industry_classifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='first_pricing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
