# Generated by Django 5.2.6 on 2026-01-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_company_first_pricing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='ev_ebitda',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
    ]
