# Generated by Django 5.2.6 on 2026-05-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_financialrecord_ev_ebitda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpc_date', models.DateField(blank=True, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('audit_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
