# Generated by Django 5.2.6 on 2026-05-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_projectdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdates',
            name='audit_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectdates',
            name='gpc_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectdates',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
