# Generated by Django 5.2.6 on 2026-01-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_chat', '0002_message_attachment_message_attachment_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='useropenaisetting',
            name='default_model',
            field=models.CharField(default='gpt-5', max_length=100),
        ),
        migrations.AlterField(
            model_name='useropenaisetting',
            name='max_tokens',
            field=models.IntegerField(default=50000),
        ),
        migrations.AlterField(
            model_name='useropenaisetting',
            name='temperature',
            field=models.FloatField(default=1),
        ),
    ]
