# Generated by Django 5.2.6 on 2026-01-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_chat', '0003_alter_message_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useropenaisetting',
            name='default_model',
            field=models.CharField(default='gpt-4.1', max_length=100),
        ),
        migrations.AlterField(
            model_name='useropenaisetting',
            name='max_tokens',
            field=models.IntegerField(default=1200),
        ),
        migrations.AlterField(
            model_name='useropenaisetting',
            name='temperature',
            field=models.FloatField(default=0.3),
        ),
    ]
