# Generated by Django 5.2.6 on 2026-04-18 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_chat', '0004_alter_useropenaisetting_default_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='document_name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='chat',
            name='has_document',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useropenaisetting',
            name='max_context_chunks',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='useropenaisetting',
            name='use_rag_for_documents',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useropenaisetting',
            name='default_model',
            field=models.CharField(default='gpt-4o', max_length=100),
        ),
        migrations.AlterField(
            model_name='useropenaisetting',
            name='max_tokens',
            field=models.IntegerField(default=1024),
        ),
        migrations.AlterField(
            model_name='useropenaisetting',
            name='temperature',
            field=models.FloatField(default=0.2),
        ),
        migrations.CreateModel(
            name='DocumentProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_pages', models.IntegerField(default=0)),
                ('processed_pages', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_processing', to='crm_chat.chat')),
            ],
            options={
                'verbose_name_plural': 'Document Processings',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('chunk_index', models.IntegerField()),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('embedding', models.BinaryField()),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=100)),
                ('char_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='crm_chat.chat')),
            ],
            options={
                'indexes': [models.Index(fields=['chat', 'page_number'], name='crm_chat_do_chat_id_e4910b_idx'), models.Index(fields=['chat', 'chunk_index'], name='crm_chat_do_chat_id_afcd3d_idx')],
            },
        ),
    ]
