# Generated by Django 5.2.6 on 2026-06-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_chat', '0005_chat_document_name_chat_has_document_message_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_processing_document',
            field=models.BooleanField(default=False),
        ),
    ]
