# Generated by Django 5.2.6 on 2026-07-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_chat', '0006_chat_is_processing_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_model', models.CharField(default='gpt-4.1', max_length=100)),
                ('temperature', models.FloatField(default=0.3)),
                ('max_tokens', models.IntegerField(default=15000)),
                ('use_rag_for_documents', models.BooleanField(default=True)),
                ('max_context_chunks', models.IntegerField(default=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='useropenaisetting',
            name='default_model',
        ),
        migrations.RemoveField(
            model_name='useropenaisetting',
            name='max_context_chunks',
        ),
        migrations.RemoveField(
            model_name='useropenaisetting',
            name='max_tokens',
        ),
        migrations.RemoveField(
            model_name='useropenaisetting',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='useropenaisetting',
            name='use_rag_for_documents',
        ),
    ]
