# Generated by Django 5.2.6 on 2026-07-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_chat', '0007_systemconfiguration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemConfiguration',
        ),
        migrations.AddField(
            model_name='useropenaisetting',
            name='default_model',
            field=models.CharField(default='gpt-4o', max_length=100),
        ),
        migrations.AddField(
            model_name='useropenaisetting',
            name='max_context_chunks',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='useropenaisetting',
            name='max_tokens',
            field=models.IntegerField(default=1024),
        ),
        migrations.AddField(
            model_name='useropenaisetting',
            name='temperature',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='useropenaisetting',
            name='use_rag_for_documents',
            field=models.BooleanField(default=True),
        ),
    ]
