# Generated by Django 5.2.6 on 2026-08-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_chat', '0008_delete_systemconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='chat_attachments/%Y/%m/%d/'),
        ),
    ]
