# Generated by Django 5.2.6 on 2026-08-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_chat', '0009_alter_message_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='chat_attachments/%Y/%m/%d/'),
        ),
    ]
