# Generated by Django 5.2.6 on 2026-06-22 17:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='articles/uploads/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=500)),
                ('document_name', models.CharField(blank=True, max_length=500)),
                ('raw_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_result', to='article_interpretation_ai.articledocument')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesOpenAISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_model', models.CharField(default='gpt-5.4-mini', max_length=100)),
                ('reasoning_effort', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('xhigh', 'X-High')], default='medium', max_length=10)),
                ('quality_reasoning_effort', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('xhigh', 'X-High')], default='high', max_length=10)),
                ('max_output_tokens', models.IntegerField(default=8000)),
                ('max_chars', models.IntegerField(default=120000)),
                ('quality_pass', models.BooleanField(default=True)),
                ('seniority_pass', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='articles_openai_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
