# Generated by Django 5.2.6 on 2026-06-23 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_interpretation_ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleGlobalOpenAISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_model', models.CharField(default='gpt-5.4-mini', max_length=100)),
                ('reasoning_effort', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('xhigh', 'X-High')], default='medium', max_length=10)),
                ('quality_reasoning_effort', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('xhigh', 'X-High')], default='high', max_length=10)),
                ('max_output_tokens', models.IntegerField(default=8000)),
                ('max_chars', models.IntegerField(default=120000)),
                ('quality_pass', models.BooleanField(default=True)),
                ('seniority_pass', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(blank=True, max_length=512)),
                ('company_name', models.CharField(blank=True, max_length=500)),
                ('document_name', models.CharField(blank=True, max_length=500)),
                ('raw_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityFieldAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_index', models.IntegerField(help_text="0-based index of the security inside raw_json['securities']")),
                ('security_name', models.CharField(blank=True, help_text='Snapshot of security_name at the time of the change', max_length=500)),
                ('field_name', models.CharField(help_text="Name of the field that was changed, e.g. 'conversion_ratio'", max_length=200)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_field_changes', to=settings.AUTH_USER_MODEL)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='article_interpretation_ai.extractionrecord')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
