# Generated by Django 5.2.6 on 2026-06-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_interpretation_ai', '0002_articleglobalopenaisetting_extractionrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionrecord',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extractionrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
