# Generated by Django 5.2.6 on 2026-05-11 12:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('system_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('has_document', models.BooleanField(default=False)),
                ('document_name', models.CharField(blank=True, max_length=512)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleai_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'system'), ('user', 'user'), ('assistant', 'assistant')], max_length=20)),
                ('content', models.TextField()),
                ('tokens', models.IntegerField(blank=True, null=True)),
                ('openai_response_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/%d/')),
                ('attachment_name', models.CharField(blank=True, max_length=512)),
                ('attachment_content_type', models.CharField(blank=True, max_length=255)),
                ('edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='articleai.chat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserOpenAISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_model', models.CharField(default='gpt-4o', max_length=100)),
                ('temperature', models.FloatField(default=0.2)),
                ('max_tokens', models.IntegerField(default=1024)),
                ('use_rag_for_documents', models.BooleanField(default=True)),
                ('max_context_chunks', models.IntegerField(default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='articleai_openai_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('chunk_index', models.IntegerField()),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('embedding', models.BinaryField()),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=100)),
                ('char_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='articleai.chat')),
            ],
            options={
                'indexes': [models.Index(fields=['chat', 'page_number'], name='articleai_d_chat_id_524a3f_idx'), models.Index(fields=['chat', 'chunk_index'], name='articleai_d_chat_id_22797f_idx')],
            },
        ),
    ]
