# Generated by Django 5.2.6 on 2026-03-24 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('announced_date', models.DateField(blank=True, null=True)),
                ('target_issuer', models.CharField(blank=True, max_length=1024, null=True)),
                ('total_transaction_value_inr', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('total_transaction_value_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('buyers_investors', models.TextField(blank=True, null=True)),
                ('sellers', models.TextField(blank=True, null=True)),
                ('ciq_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_closed_date', models.DateField(blank=True, null=True)),
                ('geography', models.CharField(blank=True, max_length=512, null=True)),
                ('ev_revenue', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('ev_ebitda', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('percent_sought', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('implied_ev_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('primary_industry', models.CharField(blank=True, max_length=512, null=True)),
                ('target_revenue', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('target_ebitda', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('acquirer_revenue', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('acquirer_ebitda', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('consideration_offered', models.CharField(blank=True, max_length=512, null=True)),
                ('target_security_type', models.CharField(blank=True, max_length=512, null=True)),
                ('accounting_method', models.CharField(blank=True, max_length=512, null=True)),
                ('deal_attitude', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('summary', models.JSONField(default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/transactions/')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_upload_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
