# Generated by Django 5.2.6 on 2026-03-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField()),
                ('classification', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
                ('auditor', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
    ]
