# Generated by Django 5.2.6 on 2026-03-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='status',
            field=models.CharField(default='processing', max_length=20),
        ),
    ]
