# Generated by Django 5.2.6 on 2026-04-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_documentchunk_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
