# Generated by Django 5.2.6 on 2026-04-21 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_documentchunk_content_hash_documentchunk_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('processed_chunks', models.IntegerField(default=0)),
                ('total_queries', models.IntegerField(default=0)),
                ('processed_queries', models.IntegerField(default=0)),
                ('current_phase', models.CharField(default='pending', max_length=50)),
                ('current_file', models.CharField(blank=True, max_length=255, null=True)),
                ('current_query', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingJobFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('total_chunks', models.IntegerField(default=0)),
                ('processed_chunks', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['status'], name='audit_docum_status_a456b0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['source'], name='audit_docum_source_1cf8b1_idx'),
        ),
        migrations.AddField(
            model_name='processingjobfile',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='audit.processingjob'),
        ),
    ]
