# Generated by Django 5.2.6 on 2026-04-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_processingjob_processingjobfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecord',
            name='question_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
