# Generated by Django 5.2.6 on 2026-04-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_auditrecord_question_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['job_id'], name='audit_docum_job_id_bbfa80_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['job_id', 'status'], name='audit_docum_job_id_a92f9d_idx'),
        ),
    ]
