# Generated by Django 5.2.6 on 2026-05-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_documentchunk_job_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecord',
            name='response_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
