# Generated by Django 5.2.6 on 2026-08-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_auditrecord_response_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
