# Generated by Django 5.2.6 on 2026-05-21 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.CharField(choices=[('gpc_screening', 'GPC Screening'), ('transaction_screening', 'Transaction Screening'), ('audit_ai', 'Audit AI'), ('ask_ai', 'Ask AI'), ('article_interpretation_ai', 'Article Interpertation AI')], max_length=30)),
                ('client_name', models.CharField(blank=True, default='', max_length=512)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.CharField(choices=[('gpc_screening', 'GPC Screening'), ('transaction_screening', 'Transaction Screening'), ('audit_ai', 'Audit AI'), ('ask_ai', 'Ask AI'), ('article_interpretation_ai', 'Article Interpretation AI')], max_length=40)),
                ('rating', models.DecimalField(choices=[(0.5, '0.5'), (1.0, '1 — Poor'), (1.5, '1.5'), (2.0, '2 — Fair'), (2.5, '2.5'), (3.0, '3 — Good'), (3.5, '3.5'), (4.0, '4 — Very Good'), (4.5, '4.5'), (5.0, '5 — Excellent')], decimal_places=1, max_digits=2)),
                ('feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='usermanagement.useractivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Workflow Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', '-created_at'], name='usermanagem_user_id_0888bf_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['workflow'], name='usermanagem_workflo_49e52b_idx'),
        ),
    ]
