# Generated by Django 5.2.6 on 2026-05-29 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_clientmaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowfeedback',
            unique_together={('user', 'workflow')},
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='workflow',
            field=models.CharField(choices=[('gpc_screening', 'GPC Screening'), ('transaction_screening', 'Transaction Screening'), ('audit_ai', 'Audit AI'), ('ask_ai', 'Ask AI'), ('article_interpretation_ai', 'Article Interpretation AI')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workflowfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='workflowfeedback',
            name='activity',
        ),
    ]
