# Generated by Django 5.2.6 on 2026-08-06 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_clientprojectsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprojectsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprojectsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='project_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='usermanagement.clientprojectsession'),
        ),
    ]
