# Generated by Django 5.2.6 on 2026-08-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_clientprojectsession_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='workflow',
            field=models.CharField(choices=[('gpc_screening', 'GPC Screening'), ('transaction_screening', 'Transaction Screening'), ('audit_ai', 'Audit AI'), ('ask_ai', 'Ask AI'), ('article_interpretation_ai', 'Article Interpretation AI'), ('ask_valuation_guide', 'Ask Valuation Guide')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workflowfeedback',
            name='workflow',
            field=models.CharField(choices=[('gpc_screening', 'GPC Screening'), ('transaction_screening', 'Transaction Screening'), ('audit_ai', 'Audit AI'), ('ask_ai', 'Ask AI'), ('article_interpretation_ai', 'Article Interpretation AI'), ('ask_valuation_guide', 'Ask Valuation Guide')], max_length=40),
        ),
    ]
