# Generated by Django 5.2.6 on 2026-06-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_valuation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='description',
            new_name='year',
        ),
    ]
