# Generated by Django 5.2.6 on 2026-07-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_valuation', '0002_rename_description_guide_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationOpenAISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_model', models.CharField(default='gpt-4.1', max_length=100)),
                ('temperature', models.FloatField(default=0.3)),
                ('max_tokens', models.IntegerField(default=15000)),
                ('use_rag_for_documents', models.BooleanField(default=True)),
                ('max_context_chunks', models.IntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Valuation OpenAI Setting',
                'verbose_name_plural': 'Valuation OpenAI Setting',
            },
        ),
    ]
