# Generated by Django 5.2.6 on 2026-08-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_valuation', '0003_valuationopenaisetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuationsession',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
